### ISSUE TITLE
Error parsing response 

### ISSUE THREAD

**Issue by vrunoa** [Urucas/adbjs#4]
Found in **adb-tcp-quick** module
[https://github.com/Urucas/adb-tcp-quick/issues/1](https://github.com/Urucas/adb-tcp-quick/issues/1)

```
/Users/vruno/.nvm/versions/io.js/v1.3.0/lib/node_modules/adb-tcp-quick-connect/node_modules/adbjs/bin/adbjs:113
          throw new Error(" " + child.stderr);
                ^
Error:  error: protocol fault (couldn't read status): Undefined error: 0

    at ADB.deviceInfo (/Users/vruno/.nvm/versions/io.js/v1.3.0/lib/node_modules/adb-tcp-quick-connect/node_modules/adbjs/bin/adbjs:113:17)
    at ADB.devices (/Users/vruno/.nvm/versions/io.js/v1.3.0/lib/node_modules/adb-tcp-quick-connect/node_modules/adbjs/bin/adbjs:61:36)
    at devices (/Users/vruno/.nvm/versions/io.js/v1.3.0/lib/node_modules/adb-tcp-quick-connect/dist/index.js:26:21)
    at Object.disconnectUI (/Users/vruno/.nvm/versions/io.js/v1.3.0/lib/node_modules/adb-tcp-quick-connect/dist/index.js:37:18)
    at Object.<anonymous> (/Users/vruno/.nvm/versions/io.js/v1.3.0/lib/node_modules/adb-tcp-quick-connect/bin/cli:15:16)
    at Module._compile (module.js:444:26)
    at Object.Module._extensions..js (module.js:462:10)
    at Module.load (module.js:339:32)
    at Function.Module._load (module.js:294:12)
    at Function.Module.runMain (module.js:485:10)
```

**Comment by vrunoa** [comment]
Deprecate library
